# Generated by Django 4.1.7 on 2023-03-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burclar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burc_adi', models.CharField(max_length=50)),
                ('aciklama', models.TextField(null=True)),
                ('aciklama_olumlu', models.TextField(null=True)),
                ('aciklama_olumsuz', models.TextField(null=True)),
                ('aciklama_guclu', models.TextField(null=True)),
                ('aciklama_zayif', models.TextField(null=True)),
                ('resim', models.ImageField(upload_to='burc_simge')),
                ('takimyildiz_adi', models.CharField(max_length=100)),
                ('takimyildiz_resim', models.ImageField(upload_to='takim_yildiz')),
                ('gezegeni', models.CharField(max_length=100)),
                ('elementi', models.CharField(max_length=100)),
                ('tarih', models.CharField(max_length=100, null=True)),
                ('niteligi', models.CharField(max_length=100, null=True)),
                ('yorumlar', models.JSONField(default=list)),
                ('mantra', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
