# Generated by Django 4.1.7 on 2023-03-25 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrolojisitem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='burclar',
            name='mantra',
        ),
    ]
