# Generated by Django 4.1.7 on 2023-03-25 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolojisitem', '0003_burclar_mantra'),
    ]

    operations = [
        migrations.AddField(
            model_name='burclar',
            name='renk',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
