# Generated by Django 4.1.7 on 2023-04-14 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrolojisitem', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
