# Generated by Django 4.1.7 on 2023-04-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolojisitem', '0006_remove_profile_bio_remove_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gun',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='yil',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
