# Generated by Django 4.1.7 on 2023-04-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolojisitem', '0009_profile_gonder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gonder',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
