# Generated by Django 4.1.7 on 2023-04-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolojisitem', '0010_alter_profile_gonder'),
    ]

    operations = [
        migrations.AddField(
            model_name='burclar',
            name='gunluk_yorum',
            field=models.TextField(null=True),
        ),
    ]
