# Generated by Django 4.1.7 on 2023-05-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolojisitem', '0011_burclar_gunluk_yorum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='burclar',
            name='yorumlar',
        ),
        migrations.AlterField(
            model_name='burclar',
            name='aciklama',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='burclar',
            name='aciklama_guclu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='burclar',
            name='aciklama_olumlu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='burclar',
            name='aciklama_olumsuz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='burclar',
            name='aciklama_zayif',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='burclar',
            name='burc_adi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='burclar',
            name='elementi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='burclar',
            name='gezegeni',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='burclar',
            name='gunluk_yorum',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='burclar',
            name='mantra',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='burclar',
            name='niteligi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='burclar',
            name='renk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='burclar',
            name='resim',
            field=models.ImageField(blank=True, null=True, upload_to='burc_simge'),
        ),
        migrations.AlterField(
            model_name='burclar',
            name='takimyildiz_adi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='burclar',
            name='takimyildiz_resim',
            field=models.ImageField(blank=True, null=True, upload_to='takim_yildiz'),
        ),
        migrations.AlterField(
            model_name='burclar',
            name='tarih',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
