# Generated by Django 4.1.7 on 2023-05-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolojisitem', '0012_remove_burclar_yorumlar_alter_burclar_aciklama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='burclar',
            name='yukselen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
