# Generated by Django 4.1.7 on 2023-05-10 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolojisitem', '0014_category_topic_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
