# Generated by Django 4.1.7 on 2023-05-10 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrolojisitem', '0015_remove_post_updated_by_topic_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='category',
        ),
    ]
