# Generated by Django 4.1.7 on 2023-05-12 13:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('astrolojisitem', '0018_post_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_likes',
            field=models.ManyToManyField(related_name='topic_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
