# Generated by Django 4.1.7 on 2023-05-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrolojisitem', '0020_post_post_resim_topic_topic_resim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_resim',
            field=models.ImageField(blank=True, null=True, upload_to='takim_yildiz'),
        ),
    ]
