# Generated by Django 4.1.7 on 2023-05-13 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('astrolojisitem', '0022_alter_topic_topic_resim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_resim',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='topic_resim',
        ),
    ]
